<?php

namespace Tests\Unit\Services\PlayerService\PlayerCreation;

use Services\PlayerService\PlayerCreation\PlayerCreate;
use Tests\TestCase;

class PlayerCreationTest extends TestCase
{
    /**
     * @var PlayerCreate
     */
    public $playerCreate;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        $this->playerCreate = new PlayerCreate();
    }

}