<?php

namespace Tests\Feature\GameSetup;

use Tests\TestCase;
use Illuminate\Foundation\Testing\RefreshDatabase;

class DatabaseInitialSeedTest extends TestCase
{
    //use RefreshDatabase;

    public function setUp(): void
    {
        parent::setUp(); // TODO: Change the autogenerated stub

        //$this->seed();
    }

    public function testBaseCitiesSeed()
    {
        $baseCities = [
            'name' => 'London',
            'country_code' => 'GBR'
        ];

        $this->assertDatabaseHas('base_cities', $baseCities);
    }

    public function testBaseClubsSeed()
    {
        $baseClubs = [
            [
                'name' => 'Arsenal',
                'country_code' => 'GBR'
            ]
        ];

        foreach ($baseClubs as $club) {
            $this->assertDatabaseHas('base_clubs', $club);
        }
    }
}