INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (1, 'London', 7285000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (2, 'Birmingham', 1013000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (3, 'Glasgow', 619680, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (4, 'Liverpool', 461000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (5, 'Edinburgh', 450180, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (6, 'Sheffield', 431607, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (7, 'Manchester', 430000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (8, 'Leeds', 424194, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (9, 'Bristol', 402000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (10, 'Cardiff', 321000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (11, 'Coventry', 304000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (12, 'Leicester', 294000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (13, 'Bradford', 289376, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (14, 'Belfast', 287500, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (15, 'Nottingham', 287000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (16, 'Kingston upon Hull', 262000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (17, 'Plymouth', 253000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (18, 'Stoke-on-Trent', 252000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (19, 'Wolverhampton', 242000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (20, 'Derby', 236000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (21, 'Swansea', 230000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (22, 'Southampton', 216000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (23, 'Aberdeen', 213070, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (24, 'Northampton', 196000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (25, 'Dudley', 192171, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (26, 'Portsmouth', 190000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (27, 'Newcastle upon Tyne', 189150, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (28, 'Sunderland', 183310, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (29, 'Luton', 183000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (30, 'Swindon', 180000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (31, 'Southend-on-Sea', 176000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (32, 'Walsall', 174739, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (33, 'Bournemouth', 162000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (34, 'Peterborough', 156000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (35, 'Brighton', 156124, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (36, 'Blackpool', 151000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (37, 'Dundee', 146690, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (38, 'West Bromwich', 146386, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (39, 'Reading', 148000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (40, 'Oldbury/Smethwick (Warley)', 145542, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (41, 'Middlesbrough', 145000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (42, 'Huddersfield', 143726, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (43, 'Oxford', 144000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (44, 'Poole', 141000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (45, 'Bolton', 139020, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (46, 'Blackburn', 140000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (47, 'Newport', 139000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (48, 'Preston', 135000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (49, 'Stockport', 132813, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (50, 'Norwich', 124000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (51, 'Rotherham', 121380, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (52, 'Cambridge', 121000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (53, 'Watford', 113080, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (54, 'Ipswich', 114000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (55, 'Slough', 112000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (56, 'Exeter', 111000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (57, 'Cheltenham', 106000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (58, 'Gloucester', 107000, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (59, 'Saint Helens', 106293, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (60, 'Sutton Coldfield', 106001, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (61, 'York', 104425, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (62, 'Oldham', 103931, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (63, 'Basildon', 100924, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (64, 'Wigan', 103608, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (65, 'Bury', 78723, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (66, 'Barnsley', 91297, 'GBR');
INSERT INTO `base_cities` (`id`, `name`, `population`, `country_code`) VALUES (67, 'Burnley', 73021, 'GBR');
