INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (1, 'Amex Stadium', 'GBR', 35, 22374);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (2, 'Anfield', 'GBR', 4, 45522);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (3, 'Ashton Gate', 'GBR', 9, 21497);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (4, 'Bramall Lane', 'GBR', 6, 32702);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (5, 'Britannia Stadium', 'GBR', 18, 27902);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (6, 'Cardiff City Stadium', 'GBR', 10, 26828);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (7, 'Carrow Road', 'GBR', 50, 27033);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (8, 'Craven Cottage', 'GBR', 1, 25700);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (9, 'DW Stadium', 'GBR', 65, 25138);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (10, 'Elland Road', 'GBR', 8, 37697);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (11, 'Emirates Stadium', 'GBR', 1, 60361);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (12, 'Etihad Stadium', 'GBR', 7, 47805);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (13, 'Ewood Park', 'GBR', 46, 31154);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (14, 'Fratton Park', 'GBR', 26, 21100);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (15, 'Gigg Lane', 'GBR', 66, 11840);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (16, 'Goodison Park', 'GBR', 4, 40157);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (17, 'Griffin Park', 'GBR', 1, 12763);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (18, 'Hillsborough', 'GBR', 6, 39812);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (19, 'KC Stadium', 'GBR', 16, 25586);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (20, 'King Power Stadium', 'GBR', 12, 32262);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (21, 'Liberty Stadium', 'GBR', 21, 20532);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (22, 'Loftus Road', 'GBR', 1, 18360);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (23, 'Memorial Stadium', 'GBR', 9, 12011);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (24, 'Molineux', 'GBR', 19, 27828);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (25, 'Oakwell', 'GBR', 67, 23009);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (26, 'Old Trafford', 'GBR', 7, 75811);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (27, 'Olympic Stadium', 'GBR', 1, 60000);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (28, 'Portman Road', 'GBR', 54, 30311);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (29, 'Pride Park', 'GBR', 20, 33597);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (30, 'Ricoh Arena', 'GBR', 11, 32609);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (31, 'Riverside', 'GBR', 41, 34988);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (32, 'Selhurst Park', 'GBR', 1, 26309);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (33, 'Seward Stadium', 'GBR', 33, 10700);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (34, 'St James Park', 'GBR', 27, 52387);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (35, 'St Mary\'s Stadium', 'GBR', 22, 32689);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (36, 'Stadium of Light', 'GBR', 28, 49000);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (37, 'Stamford Bridge', 'GBR', 1, 41837);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (38, 'The Galpharm Stadium', 'GBR', 42, 24500);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (39, 'The Hawthorns', 'GBR', 38, 26272);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (40, 'The Valley', 'GBR', 1, 27111);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (41, 'Turf Moor', 'GBR', 68, 22546);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (42, 'University of Bolton Stadium', 'GBR', 45, 28723);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (43, 'Valley Parade', 'GBR', 13, 25136);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (44, 'Vicarage Road', 'GBR', 53, 17477);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (45, 'Villa Park', 'GBR', 2, 42788);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (46, 'Wembley', 'GBR', 1, 90000);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (47, 'White Hart Lane', 'GBR', 1, 36230);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (48, 'Brentford Community Stadium', 'GBR', 1, 17250);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (49, 'City Ground', 'GBR', 15, 30445);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (50, 'The Den', 'GBR', 1, 20146);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (51, 'Deepdale Stadium', 'GBR', 48, 23404);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (52, 'Madejski Stadium', 'GBR', 39, 24161);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (53, 'Kirklees Stadium', 'GBR', 42, 24500);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (54, 'Power Court Stadium', 'GBR', 29, 23000);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (55, 'St Andrew\'s Stadium', 'GBR', 2, 29409);
INSERT INTO `base_stadiums` (`id`, `name`, `country_code`, `city_id`, `capacity`) VALUES (56, 'Kenilworth Road', 'GBR', 29, 10356);
