INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (1, 'Center back', 'CB');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (2, 'Left back', 'LB');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (3, 'Left wingback', 'LWB');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (4, 'Right back', 'RB');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (5, 'Right wingback', 'RWB');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (6, 'Defensive midfield center', 'DMC');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (7, 'Center midfielder', 'CM');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (8, 'Left wing', 'LW');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (9, 'Left forward', 'LF');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (10, 'Attacking midfield center', 'AMC');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (11, 'Right wing', 'RW');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (12, 'Right forward', 'RF');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (13, 'Center forward', 'CF');
INSERT INTO `positions` (`id`, `name`, `alias`) VALUES (14, 'Striker', 'ST');
